import { z } from 'zod';

export const UserScalarFieldEnumSchema = z.enum([
  'id',
  'email',
  'stripeCustomerId',
  'name',
  'sex',
  'socialName',
  'cpf',
  'rg',
  'passport',
  'phoneNumber',
  'birthDate',
  'nationality',
  'diet',
  'foodRestriction',
  'type',
  'emergencyContactName',
  'emergencyContactPhoneNumber',
  'educationLevel',
  'currentYear',
  'languagesSimulates',
  'advisorRole',
  'facebook',
  'instagram',
  'linkedin',
  'leader',
  'delegationId',
  'createdAt',
  'updatedAt',
]);
